-- Warranty invoices and shared Product Master integration.
alter table public.products add column if not exists pack_size text;
alter table public.doctor_entries add column if not exists product_id uuid references public.products(id) on delete set null;
alter table public.company_settings add column if not exists warranty_authorized_person text;
alter table public.company_settings add column if not exists warranty_business_address text;
create table if not exists public.warranty_invoices (id uuid primary key default gen_random_uuid(),invoice_number text not null unique,customer_id uuid references public.customers(id) on delete set null,customer_name_snapshot text not null,customer_address_snapshot text,invoice_date date not null default current_date,city text,sector text,salesman text,phone text,username text,summary_no text,page_label text not null default '1 of 1',x_discount numeric not null default 0,grn_amount numeric not null default 0,credit_note numeric not null default 0,gross_amount numeric not null default 0,total_discount numeric not null default 0,total_sales_tax numeric not null default 0,total_advance_tax numeric not null default 0,net_amount numeric not null default 0,created_at timestamptz not null default now());
create table if not exists public.warranty_invoice_items (id uuid primary key default gen_random_uuid(),warranty_invoice_id uuid not null references public.warranty_invoices(id) on delete cascade,product_id uuid references public.products(id) on delete set null,qty numeric not null check(qty>0),bns numeric not null default 0 check(bns>=0),description text not null,pack text,batch_number text,expiry_date date,rate numeric not null check(rate>=0),sales_tax numeric not null default 0 check(sales_tax>=0),advance_tax numeric not null default 0 check(advance_tax>=0),discount_percent numeric not null default 10 check(discount_percent between 0 and 100),amount numeric generated always as(qty*rate) stored,net_amount numeric generated always as((qty*rate)-((qty*rate)*discount_percent/100)-sales_tax-advance_tax) stored,created_at timestamptz not null default now());
create or replace function public.generate_next_warranty_invoice_number() returns text language plpgsql security invoker set search_path=public as $$ declare n bigint; begin lock table public.warranty_invoices in share row exclusive mode; select coalesce(max(substring(invoice_number from '^INV([0-9]+)$')::bigint),0)+1 into n from public.warranty_invoices where invoice_number ~ '^INV[0-9]+$'; return 'INV'||lpad(n::text,6,'0'); end $$;
alter table public.warranty_invoices alter column invoice_number set default public.generate_next_warranty_invoice_number();
create index if not exists doctor_entries_product_idx on public.doctor_entries(product_id); create index if not exists warranty_invoices_date_idx on public.warranty_invoices(invoice_date); create index if not exists warranty_invoice_items_invoice_idx on public.warranty_invoice_items(warranty_invoice_id);
alter table public.warranty_invoices enable row level security; alter table public.warranty_invoice_items enable row level security;
create policy "Authenticated users have full access to warranty invoices" on public.warranty_invoices for all to authenticated using(auth.role()='authenticated') with check(auth.role()='authenticated');
create policy "Authenticated users have full access to warranty invoice items" on public.warranty_invoice_items for all to authenticated using(auth.role()='authenticated') with check(auth.role()='authenticated');
grant select,insert,update,delete on public.warranty_invoices,public.warranty_invoice_items to authenticated; revoke all on function public.generate_next_warranty_invoice_number() from public; grant execute on function public.generate_next_warranty_invoice_number() to authenticated;
