import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { drawBrandHeader, type CompanySettings } from './pdfBranding'
export type WarrantyLine={qty:number;bns:number;description:string;pack:string;batch_number:string;expiry_date:string;rate:number;sales_tax:number;advance_tax:number;discount_percent:number}
export type WarrantyData={invoice_number:string;customer_name_snapshot:string;customer_address_snapshot:string;invoice_date:string;city:string;sector:string;salesman:string;phone:string;username:string;summary_no:string;page_label:string;x_discount:number;grn_amount:number;credit_note:number;items:WarrantyLine[];authorizedPerson?:string;businessAddress?:string}
const number=(value:number)=>Number(value)||0
const currency=(value:number)=>`Rs ${number(value).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2})}`
async function imageData(url:string){const response=await fetch(url);if(!response.ok)throw new Error('Image unavailable');const blob=await response.blob();return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
export async function generateWarrantyPdf(data:WarrantyData,company:CompanySettings){
 const doc=new jsPDF({orientation:'landscape'});await drawBrandHeader(doc,company,'WARRANTY INVOICE',{companyNameHeading:true});doc.setFontSize(9);doc.setTextColor(30,41,59);doc.setFont('helvetica','bold');doc.text(`Invoice No: ${data.invoice_number}`,14,44);doc.text(`Date: ${data.invoice_date}`,282,44,{align:'right'});doc.text(`M/s: ${data.customer_name_snapshot}`,14,51);doc.setFont('helvetica','normal');doc.text(`Address: ${data.customer_address_snapshot||'-'}`,14,57);doc.text(`City: ${data.city||'-'}   Sector: ${data.sector||'-'}   Salesman: ${data.salesman||'-'}`,146,51);doc.text(`Phone: ${data.phone||'-'}   UserName: ${data.username||'-'}`,146,57);doc.text(`Summary No: ${data.summary_no||'-'}   Page ${data.page_label||'1 of 1'}`,282,57,{align:'right'});
 const rows=data.items.map(item=>{const amount=number(item.qty)*number(item.rate),discount=amount*number(item.discount_percent)/100,net=amount-discount-number(item.sales_tax)-number(item.advance_tax);return[item.qty,item.bns,item.description,item.pack||'-',item.batch_number||'-',currency(item.rate),currency(amount),currency(item.sales_tax),currency(item.advance_tax),`${number(item.discount_percent).toFixed(2)}%`,currency(net)]});
 autoTable(doc,{startY:63,head:[['Qty','Bns','Description','Pack','Batch#','Rate','Amount','S-Tax','A-Tax','Discount','Net Amount']],body:rows,theme:'grid',margin:{left:14,right:14},styles:{fontSize:7,cellPadding:2,textColor:[30,41,59]},headStyles:{fillColor:[7,18,35],textColor:255,fontStyle:'bold'},alternateRowStyles:{fillColor:[242,245,249]},columnStyles:{2:{cellWidth:50},10:{cellWidth:27}}});
 const gross=data.items.reduce((s,x)=>s+number(x.qty)*number(x.rate),0),discount=data.items.reduce((s,x)=>s+number(x.qty)*number(x.rate)*number(x.discount_percent)/100,0),salesTax=data.items.reduce((s,x)=>s+number(x.sales_tax),0),advanceTax=data.items.reduce((s,x)=>s+number(x.advance_tax),0),net=gross-discount-number(data.x_discount)-number(data.grn_amount)-number(data.credit_note)-salesTax-advanceTax;
 const totalsY=Math.max(125,(doc as any).lastAutoTable.finalY+10),labels=['Gross Amount','Discount','X. Discount','GRN Amount','Credit Note','Sales Tax','Advance Tax'],values=[gross,discount,data.x_discount,data.grn_amount,data.credit_note,salesTax,advanceTax];labels.forEach((label,index)=>{const y=totalsY+index*5;doc.text(label,228,y);doc.text(currency(number(values[index])),282,y,{align:'right'})});const netY=totalsY+37;doc.setFillColor(7,18,35);doc.rect(224,netY-4,60,10,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.text('NET AMOUNT',228,netY+2);doc.text(currency(net),282,netY+2,{align:'right'});
 doc.setTextColor(30,41,59);doc.setFontSize(8);doc.text(`NO. OF ITEMS: ${data.items.length}`,14,totalsY+2);doc.line(14,totalsY+6,215,totalsY+6);const person=data.authorizedPerson||company.warranty_authorized_person||company.admin_name||'[Authorized person name]',address=data.businessAddress||company.warranty_business_address||company.address||'[address]';const clause=`WARRANTY under section 23(1)(i) of the Drug Act 1976. ${person}, being a person resident in Pakistan carrying on business at ${address} under the name Synaxis Health Care and being an authorised agent of the drugs, do hereby give this warranty that the drug sold by us do not contravene in any way the provisions of section 23 of the drug act 1976.`;doc.setFont('helvetica','bold');doc.text('WARRANTY',14,totalsY+13);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(doc.splitTextToSize(clause,195),14,totalsY+18);doc.text('Note: For dated items we must be informed six months prior to expiry.',14,totalsY+33);doc.text('Note: Herbal, Food, Unani, Cosmetic, Nutritional & Hemoproducts do not fall under this warranty.',14,totalsY+38);
 try{const urduClause=await imageData('/assets/image.png');doc.addImage(urduClause,'PNG',55,totalsY+40,78,12,undefined,'FAST')}catch{/* keep English warranty text if optional artwork is unavailable */}
 const signatureBlock={left:238,width:46,center:261};const signatureWidth=34,signatureHeight=14;try{const signature=await imageData('/assets/signature.png');doc.addImage(signature,'PNG',signatureBlock.center-signatureWidth/2,171,signatureWidth,signatureHeight,undefined,'FAST')}catch{/* retain labelled signature area */}doc.setFontSize(7);doc.text(`Printed: ${new Date().toLocaleString('en-PK')}`,14,198);doc.line(signatureBlock.left,188,signatureBlock.left+signatureBlock.width,188);doc.setFont('helvetica','bold');doc.text(`For ${company.company_name}`,signatureBlock.center,192,{align:'center'});doc.setFont('helvetica','normal');doc.text('Authorized Signature',signatureBlock.center,197,{align:'center'});return doc
}

